stages:
  - build-containers
  - deploy

####################################################
## TerminalMirror Live
build-docker-image:
  stage: build-containers
  only:
    - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    # Setup login credentials
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - mv $ENV_FILE $CI_PROJECT_DIR/.env
#    - ls -al $CI_PROJECT_DIR;
    - /kaniko/executor --single-snapshot --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.docker/Dockerfile --destination $CI_REGISTRY/base:master
  tags:
    - kubernetes-runner

## TerminalMirror Live
####################################################
