stages:
  - build-containers
  - deploy

####################################################
## terminalmirror build live container

# build-docker-image:
#   stage: build-containers
#   only:
#     - master
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   script:
#     # Setup login credentials
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
#     - mv $ENV_FILE $CI_PROJECT_DIR/.env
# #    - ls -al $CI_PROJECT_DIR;
#     - /kaniko/executor --single-snapshot --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.docker/Dockerfile --destination $CI_REGISTRY/base:master
#   tags:
#     - kubernetes-runner

## terminalmirror build live container
####################################################

####################################################
## deploy live container
all.dev-kube.leafletcomms.co.uk-deployment:
  stage: deploy
  only:
    - master
  image: bitnami/kubectl:1.16.2
  script:
    - cat $KUBE_CONFIG
    - mv -r $KUBE_CONFIG ~/.kube/config
    - cat .kubernetes/terminal-mirror-deployment.yaml | sed "s/%DATE%/$(date '+%Y-%m-%d')/g" | sed "s/\$CI_COMMIT_SHORT_SHA/${CI_COMMIT_SHORT_SHA/}/g" | kubectl apply -f -
  tags:
    - kubernetes-runner
## deploy live container
####################################################
