apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-mirror-com
  annotations:
    kubernetes.io/change-cause: "%DATE% sha: $CI_COMMIT_SHORT_SHA"
  labels:
    app: terminal-mirror-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal-mirror-com
  template:
    metadata:
      name: terminal-mirror-com
      labels:
        app: terminal-mirror-com
    spec:
      imagePullSecrets:
        - name: core.harbor.kubernetes.netblink.pl
      containers:
      - name: apache-terminal-mirror-com
        image: core.harbor.kubernetes.netblink.pl/terminal-mirror/base:master
        env:
        - name: APP_ENV
          value: production
        - name: CI_COMMIT_SHORT_SHA
          value: "$CI_COMMIT_SHORT_SHA"
        imagePullPolicy: Always
        ports:
        - containerPort: 80

      - name: curl-terminal-mirror-com
        image: core.harbor.kubernetes.netblink.pl/terminal-mirror/base:master
        env:
        - name: APP_ENV
          value: production
        - name: CI_COMMIT_SHORT_SHA
          value: "$CI_COMMIT_SHORT_SHA"
        - name: APP_SERVER_PORT
          value: "3006"
        imagePullPolicy: Always
        command: ["bash","-c"]
        args: ["cd /share && php artisan server:curl-in debug"]
        ports:
        - containerPort: 3006

      - name: ws-terminal-mirror-com
        image: core.harbor.kubernetes.netblink.pl/terminal-mirror/base:master
        env:
        - name: APP_ENV
          value: production
        - name: CI_COMMIT_SHORT_SHA
          value: "$CI_COMMIT_SHORT_SHA"
        - name: WEBSOCKET_SERVER_PORT
          value: "3005"
        imagePullPolicy: Always
        command: ["bash","-c"]
        args: ["cd /share && php artisan server:terminal debug"]
        ports:
        - containerPort: 3005

      - name: redis-trminal-mirror-com
        image: redis:5.0.12
        ports:
        - containerPort: 6379
