version: '3.3'

services:
  web:
    container_name: terminal-mirror
    restart: always
    build:
      dockerfile: .docker/web/Dockerfile
      context: ..
      args:
        - USERNAME=${USERNAME:-ubuntu}
        - UID=${UID:-1000}
        - GROUP=${GROUP:-root}
    ports:
      - "${WEB_PORT:-80}:80"
      - "${APP_SERVER_PORT:-3005}:3005"
      - "${WEBSOCKET_SERVER_PORT:-3003}:3003"
    volumes:
      - ../:/var/www
    entrypoint: ["/var/www/.docker/web/entrypoint.sh"]
